### ISSUE TITLE
Publishing repository so it can be cited

### ISSUE THREAD

**Issue by aashayarora** [opensciencegrid/osg-ca-generator#24]
Can this repository be published as is suggested here:

https://guides.github.com/activities/citable-code/

So it can be cited in papers.

Thank You

**Comment by bbockelm** [comment]
@brianhlin - can you handle this when you get back?

**Comment by brianhlin** [comment]
@aaarora Done!

[![DOI](https://zenodo.org/badge/54154946.svg)](https://zenodo.org/badge/latestdoi/54154946)
